spring.application.name=gym-management

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.health.show-components=always
management.prometheus.metrics.export.enabled=true

# Info endpoint
info.app.name=Gym Management REST API
info.app.version=1.0.0
info.app.description=Trainee and Trainer management system

# Logging
logging.pattern.console=%d{HH:mm:ss} [%X{transactionId}] %-5level %logger{36} - %msg%n