# Production environment

spring.datasource.url=jdbc:h2:file:./data/gym_prod;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=prod_strong_pass

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

logging.level.com.epam.rest=WARN
logging.level.org.hibernate.SQL=WARN